<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VictusControl.Application\VictusControl.Application.csproj" />
    <ProjectReference Include="..\VictusControl.Domain\VictusControl.Domain.csproj" />
    <ProjectReference Include="..\VictusControl.Hardware.Abstractions\VictusControl.Hardware.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
