namespace GHelper.Hardware.Hp;

public static class HpDiagnosticDashboardFormatter
{
    public const string NotAvailable = "Not available";
    public const string LegacyReportSchema = "Legacy / unknown";
    public const string RawFanLevelWarning = "Raw values are not RPM or percent.";
    public const string FanControlStatus = "Blocked - " + HpDiagnosticStatusText.FanControlNotImplemented;
    public const string SetFanMaxStatus = HpDiagnosticStatusText.SetFanMaxNoGo;
    public const string SetFanMaxReadinessStatus = "NO-GO";
    public const string SetFanMaxInputLengthUnset = "Unset / not validated";
    public const string SetFanMaxPayloadLengthNotSelected = "Not selected";
    public const string SetFanMaxEvidenceMissing = "Missing / not proven";

    public static HpDiagnosticDashboardHealthSummary BuildHealthSummary(HpDiagnosticDashboardInput input)
    {
        return new HpDiagnosticDashboardHealthSummary(
            input.IsHpVictusDetected == true ? "Ready" : NotAvailable,
            ClassifyAvailability(
                input.RootWmiReadiness,
                input.HpqBIntMReadiness,
                input.HpqBDataInReadiness,
                input.CimRootWmiReadiness,
                input.CimHpqBIntMReadiness,
                input.CimMethodMetadataReadiness),
            ClassifyAvailability(input.SystemDesignDataDecodeStatus, input.SoftwareFanControlSupport),
            ClassifyAvailability(input.FanCount, input.MaxFanState, input.Fan1RawLevel, input.Fan2RawLevel),
            SetFanMaxStatus);
    }

    public static string FormatHealthSummary(HpDiagnosticDashboardHealthSummary summary)
    {
        return "Health: Device " + summary.DeviceStatus +
            " | WMI/CIM " + summary.WmiCimStatus +
            " | Telemetry " + summary.ReadOnlyTelemetryStatus +
            " | Fan read-only " + summary.FanReadOnlyStatus +
            " | Fan control " + summary.FanControlStatus;
    }

    public static IReadOnlyList<HpDiagnosticDashboardSection> BuildSections(HpDiagnosticDashboardInput input)
    {
        return
        [
            new("Report metadata",
            [
                Row("Schema version", FormatReportSchemaVersion(input.ReportSchemaVersion)),
                Row("Generated by", input.ReportGeneratedBy),
                Row("Report mode", input.ReportMode),
                Row("Report source", input.ReportSource),
                Row("Last generated", FormatReportTimestamp(input.ReportGeneratedAt))
            ]),
            new("Device",
            [
                Row(HpDiagnosticStatusText.ReadOnlyDiagnostic, "Cached report and startup snapshot only; no UI action invokes WMI."),
                Row("HP/Victus detected", input.IsHpVictusDetected == true ? "Detected" : NotAvailable),
                Row("Manufacturer", input.Manufacturer),
                Row("Model", input.Model),
                Row("SKU", input.Sku),
                Row("BIOS version", input.BiosVersion)
            ]),
            new("WMI/CIM readiness",
            [
                Row(@"root\wmi", input.RootWmiReadiness),
                Row("hpqBIntM", input.HpqBIntMReadiness),
                Row("hpqBDataIn", input.HpqBDataInReadiness),
                Row(@"CIM root\wmi", input.CimRootWmiReadiness),
                Row("CIM hpqBIntM", input.CimHpqBIntMReadiness),
                Row("CIM method metadata", input.CimMethodMetadataReadiness)
            ]),
            new("Read-only telemetry",
            [
                Row("SystemDesignData decoded", input.SystemDesignDataDecodeStatus),
                Row("Software fan control declared by firmware", input.SoftwareFanControlSupport)
            ]),
            new("Fan read-only status",
            [
                Row("Fan count", input.FanCount),
                Row("Max fan state", input.MaxFanState),
                Row("Fan 1 raw level byte", input.Fan1RawLevel),
                Row("Fan 2 raw level byte", input.Fan2RawLevel),
                Row("Raw level data", RawFanLevelWarning)
            ]),
            new("SetFanMax evidence readiness",
            [
                Row("Current status", SetFanMaxReadinessStatus),
                Row("Fan write implemented", FormatEvidenceWriteImplemented(input.SetFanMaxWriteImplemented)),
                Row("Fan write allowed", FormatEvidenceWriteAllowed(input.SetFanMaxWriteAllowed)),
                Row("DeviceValidatedInputLength", FormatDeviceValidatedInputLength(input.SetFanMaxDeviceValidatedInputLength)),
                Row("Payload length decision", SetFanMaxPayloadLengthNotSelected),
                Row("Exact device payload length", SetFanMaxEvidenceMissing),
                Row("Restore/disable behavior proof", SetFanMaxEvidenceMissing),
                Row("Thermal observation proof", SetFanMaxEvidenceMissing),
                Row("AC/battery/power-state proof", SetFanMaxEvidenceMissing),
                Row("Failure/recovery proof", SetFanMaxEvidenceMissing),
                Row("Human approval checkpoint", SetFanMaxEvidenceMissing),
                Row("Report blocked reason", input.SetFanMaxBlockedReason),
                Row("Report next required proof", input.SetFanMaxNextRequiredProof)
            ]),
            new("Safety / NO-GO status",
            [
                Row("Fan control", FanControlStatus),
                Row("SetFanMax", SetFanMaxStatus),
                Row("SetFanMax write implemented", input.SetFanMaxWriteImplemented),
                Row("SetFanMax write allowed", input.SetFanMaxWriteAllowed),
                Row("Blocked reason", input.SetFanMaxBlockedReason),
                Row("Next required proof", input.SetFanMaxNextRequiredProof)
            ]),
            new("Missing-data guidance",
            [
                Row("Explicit probe data", HpDiagnosticStatusText.NormalHpModeDoesNotRunExplicitProbes),
                Row("Developer-only tests", HpDiagnosticStatusText.ExplicitTestsAreDeveloperOnly),
                Row("Fan control", HpDiagnosticStatusText.FanControlNotImplemented),
                Row("SetFanMax", HpDiagnosticStatusText.SetFanMaxNoGo)
            ])
        ];
    }

    public static string BuildSummary(HpDiagnosticDashboardInput input)
    {
        return string.Join(
            Environment.NewLine,
            BuildSections(input)
                .SelectMany(section => section.Rows)
                .Select(row => row.Label + ": " + row.Value));
    }

    public static string FormatCimReadiness(bool? value) => value switch
    {
        true => "Ready",
        false => NotAvailable,
        _ => NotAvailable
    };

    public static string FormatWriteImplementationStatus(bool? value) => value switch
    {
        true => "Implemented",
        false => "Not implemented",
        _ => NotAvailable
    };

    public static string FormatWriteAllowedStatus(bool? value) => value switch
    {
        true => "Allowed",
        false => "Blocked",
        _ => NotAvailable
    };

    public static string FormatDeviceValidatedInputLength(string? value)
    {
        return int.TryParse(value, out int length) && length is 1 or 4
            ? length + (length == 1 ? " byte reported; not approved" : " bytes reported; not approved")
            : SetFanMaxInputLengthUnset;
    }

    private static string FormatEvidenceWriteImplemented(string? value)
    {
        return string.Equals(value, "Implemented", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, bool.TrueString, StringComparison.OrdinalIgnoreCase)
            ? "Blocked - unexpected implemented state"
            : "False - not implemented";
    }

    private static string FormatEvidenceWriteAllowed(string? value)
    {
        return string.Equals(value, "Allowed", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, bool.TrueString, StringComparison.OrdinalIgnoreCase)
            ? "Blocked - unexpected allowed state"
            : "False - blocked";
    }

    public static string FormatReportSchemaVersion(string? value)
    {
        return int.TryParse(value, out int version) && version > 0
            ? "v" + version
            : LegacyReportSchema;
    }

    public static string FormatReportTimestamp(string? value)
    {
        return DateTimeOffset.TryParse(value, out DateTimeOffset timestamp)
            ? timestamp.ToString("yyyy-MM-dd HH:mm:ss zzz", System.Globalization.CultureInfo.InvariantCulture)
            : NotAvailable;
    }

    private static HpDiagnosticDashboardRow Row(string label, string? value)
    {
        string displayValue = string.IsNullOrWhiteSpace(value) ? NotAvailable : value;
        return new HpDiagnosticDashboardRow(label, displayValue, GetStatus(displayValue));
    }

    private static string ClassifyAvailability(params string?[] values)
    {
        int availableCount = values.Count(value => !string.IsNullOrWhiteSpace(value) &&
            !string.Equals(value, NotAvailable, StringComparison.OrdinalIgnoreCase));

        return availableCount switch
        {
            0 => NotAvailable,
            _ when availableCount == values.Length => "Ready",
            _ => "Partial"
        };
    }

    private static HpDiagnosticDashboardStatus GetStatus(string value)
    {
        if (value.StartsWith("Ready", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Succeeded", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Enabled", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Declared", StringComparison.OrdinalIgnoreCase))
        {
            return HpDiagnosticDashboardStatus.Ready;
        }

        if (value.StartsWith("Blocked", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("NO-GO", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("False - blocked", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Missing", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Unset", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("Not selected", StringComparison.OrdinalIgnoreCase))
        {
            return HpDiagnosticDashboardStatus.Blocked;
        }

        return HpDiagnosticDashboardStatus.Normal;
    }
}
